// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XlykGrLwYvd8--QiGmGGkHq2zbpAsGI',
    appId: '1:463718666166:web:e315434d51057dc3c67b17',
    messagingSenderId: '463718666166',
    projectId: 'pesa-app-d7a9d',
    authDomain: 'pesa-app-d7a9d.firebaseapp.com',
    storageBucket: 'pesa-app-d7a9d.appspot.com',
    measurementId: 'G-GZJZMHP659',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAIxPku99oeU-JufzHUJQDbRirZKqbgE0',
    appId: '1:463718666166:android:79b15c92b7c86968c67b17',
    messagingSenderId: '463718666166',
    projectId: 'pesa-app-d7a9d',
    storageBucket: 'pesa-app-d7a9d.appspot.com',
  );
}
